### ISSUE TITLE
Cookie banner layouts broken after upgrade to version 6.0.0

### ISSUE THREAD

**Issue by codeandflow** [Really-Simple-Plugins/complianz-gdpr#337] opened 2022-01-11 13:08 UTC
Hi team,
On two different pages, we had bigger layout issues with the cookie banner after upgrading to version 6.0.0 some hours ago.
In case 1), a huge full-size blue "X" was overlaying the whole page.
in case 2), the height of the cookie banner increased by factor 3

Many thanks in advance for dealing with this.
BR, Flo + team.

Screenshots:
![image](https://user-images.githubusercontent.com/81447519/148947945-82e78f20-38ee-4879-8f72-4fd6b49d03bc.png)

**Comment by rlankhorst** [comment] 2022-01-11 19:08
Hi @codeandflow, 

Banner width: can you check if this branch resolves the issue?
https://github.com/Really-Simple-Plugins/complianz-gdpr/compare/auto-adjust-width-bug?expand=1

The current update includes an issue where the banner width keeps increasing the width. After setting the banner width to a good size the issue should be gone after this update.

**Comment by rlankhorst** [comment] 2022-01-11 19:10
As for the huge "x", can you share the domain? It is possibly some custom css from your theme, or the cookie banner css is not generated. You can try to generate it by saving the banner settings. If it's theme css, I can make sure to override that css in the next update, and provide you with a fix in the meantime.

**Comment by codeandflow** [comment] 2022-01-11 22:21
Thx Rogier for quick response.
I can share the urls, yes. For your understanding: We are using different non-listed urls for our servers.
Working Backup on REF environment (complianz 5.5.3): webshop-profis.de 
Problematic DEV environment (complianz 6.0.0): weltenhelden.com
After deactivating and reactivating the pluin, the X disappeared, the layout of the cookie banner is still problematic
(you can see the difference directly by comparing the 2 sites).
Thx in advance, Flo + team.

**Comment by rlankhorst** [comment] 2022-01-12 08:23
It looks like your banner is set to the categories type "hidden", but this type isn't available anymore. Can you select "view preferences" in the banner, then save again?

**Comment by codeandflow** [comment] 2022-01-12 21:06
OK, we were now comparing both configurations in detail (5.5.3 vs. 6.0.0).
we could directly found several issues 
- It seems to be the case that not only our template "minimal" was removed, but moreover the whole option "template"
- menu options like "imprint" were removed, too 
- some values were just deleted, e. g. "test on the manage constent tab" or "dismiss cookies text" (which is now "deny button" and also empty).
Well, we guess that would not only bother us, to be honest ;-)

Most important question for us: Could you bring the template "minimal" back?
Thx in advance,
Flo + team

**Comment by rlankhorst** [comment] 2022-01-13 09:52
The templates will be reinstated in a future version in a different form, which will offer several presets for different setups. In the meantime you can adjust the settings manually. Resetting to default should get you a similar banner. 

I'm not sure what you mean with "menu options like imprint were removed"? You can still select a document for the imprint. As of version 6.0.1 this will also show up as link on the cookie banner. 

The empty buttons is incorrect behaviour of course. I suspect this may be caused by php 8 issues, which should be resolved with the 6.0.1 update. Can you try upgrading, do a reset on the banner settings, then re-saving?

**Comment by codeandflow** [comment] 2022-01-15 15:27
The reset to default values ...
- has not reset the layout to the minimal style, but helped to improve the layout, thx.
- We would highly recommend to bring this back as no one likes huge cookie banners, especially not on a mobile phone.

- By accident ;-), we have seen your new post complianz.io/css-lesson-19-the-minimal-bottom-banner-revisited/, thx for this,
review comments for this script:
- - the code has a typo as a ":" is missing after min-width for the last statement
- - to really have the result of a minimal layout, e. g. the following statement is missing in the code, too:
     .cmplz-information, .cmplz-header, .cmplz-logo, .cmplz-close { display:none; }

- Another finding: The css patterns have changed. I guess this is the main reason why our layout was destroyed.
  It has changed from .cc-* to .cmplz-*. With this information, we can also fix our custom css, again.
- BTW, your plugin is also still prefilling the custom css box with the old css code (.cc-accept-all instead of .cmplz-*)

Still working on that, happy to beta test your code :-D
Nevertheless, thx for your work, of course!

BR, Flo + team

**Comment by rlankhorst** [comment] 2022-01-17 15:41
Hi @codeandflow, 

Thanks for all your input, we'll update the article. 

As for the prefilled css: that is because it was saved in the old plugin. If you clear it completely, it will get filled with the new css.

**Closed** 2022-01-27 08:41 UTC
