### ISSUE TITLE
TrustPulse support is incomplete

### ISSUE THREAD

**Issue by thebrandonallen** [Really-Simple-Plugins/complianz-gdpr#380] opened 2022-10-27 21:42 UTC
The standard TrustPulse embed code look like the below

```html
<script type="text/javascript" src="https://a.trstplse.com/app/js/api.min.js" data-account="805" async></script>
```

The `data-account` attribute is required for the script to work, but it is not added to the TrustPulse script once tag consent is given, and the script tag is added back to the DOM.

I did some quick poking around/testing, but couldn't find the solution. I'm happy to write up a PR to fix this if someone can point me in the right direction.

**Comment by rlankhorst** [comment] 2022-10-28 11:06
Hi @thebrandonallen, 

The issue is probably that the data attributes aren't copied over to the script element that is added to the DOM. I'll have a look.

**Comment by rlankhorst** [comment] 2022-10-28 11:23
@thebrandonallen can you try this branch?

https://github.com/Really-Simple-Plugins/complianz-gdpr/compare/copy-script-attributes-to-target-script?expand=1

It copies over all attributes of a script that is being enabled.

**Comment by thebrandonallen** [comment] 2022-10-28 15:59
Thanks for getting back so quickly!

I tested that branch, and it's not working quite right. The problem is that the script is never appended to the `<head>` tag. 

I did figure out that this hinges on whether or not `data-category` is present. If I updated `cmplzCopyAttributes` to ignore `data-category` the script would append to the DOM correctly. This still leaves behind `data-service` and `cmplz-activated` class (see below):
```html
<script src="https://a.trstplse.com/app/js/api.min.js?ver=6.0.3" data-service="general" data-account="805" async="" data-id="trustpulse-api-js-js" class="cmplz-activated"></script>
```
This version of the TrustPulse script tag worked correctly.

**Comment by rlankhorst** [comment] 2022-10-31 08:49
Ok, thanks for testing. That skipping the data-category is necessary is strange, I'll have to look into that.

**Comment by rlankhorst** [comment] 2022-11-07 13:20
Hi @thebrandonallen, I'm looking into this branch at the moment, I can't reproduce the issue you're experiencing. When I add the URL to the script center, it gets blocked. Then on accepting, it is added to the head, regardless of if I skip the category attribute. Do you maybe have a sandbox where I can view it in not working state?

**Comment by rlankhorst** [comment] 2022-12-05 11:59
@thebrandonallen this branch is about to be released on the wordpress repo, expected next week.

**Comment by rlankhorst** [comment] 2022-12-17 20:10
This has been merged in the latest release.

**Closed** 2022-12-17 20:10 UTC
